version: '3.9'

services:
  test-cicd:
    build: .
    container_name: test-cicd
    restart: unless-stopped
    ports:
      - 7001:7001
    volumes:
      - ./static:/opt/static
    networks:
      - localnet 
    
networks:
  localnet:
    external: true
    name: localnet
