name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    linter-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v4
              with:
                go-version: 1.21
                cache: false
                
            - name: lint
              uses: golangci/golangci-lint-action@v3
              with:
                version: v1.54.0
    deploy:
        runs-on: ubuntu-latest
        needs: linter-check
        steps:
          - name: Executing remote ssh commands using password
            uses: appleboy/ssh-action@v1.0.0
            with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.SERVER_USER }}
                password: ${{ secrets.SERVER_PASSWD }}
                port: 22
                script: |
                    cd /app/Golang-CICD  
                    git pull
                    task build
                    