name: Build and Publish

on:
  push:
    branches: [ main ]

jobs:
  build-and-opublish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        run: docker build . --tag test-image:$(date +%s)

      - name: Publish to registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: jedis/go-github-actions
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
